# Generated by Django 4.2.5 on 2023-10-20 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=150)),
                ('website', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tagline', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('avg_rating', models.FloatField(default=0)),
                ('no_of_rating', models.FloatField(default=0)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream', to='stream.streams')),
            ],
        ),
    ]
